code/espurna/rfbridge.ino

This PR got lost in the migration from BitBucket to GitHub (I think, but the bitbucket interface is a little hard to understand).
First PR on this repo! 🎉 🎆

Used the constant for RF_MESSAGE_SIZE.

---

code/espurna/config/arduino.h
code/espurna/config/general.h
code/espurna/config/hardware.h
code/espurna/espurna.ino
code/espurna/uart_mqtt

Adds support to send data over MQTT to UART and from UART to MQTT

UART<->MQTT

---

.travis.yml
code/espurna/config/hardware.h
code/espurna/config/sensors.h
code/espurna/settings.ino
code/platformio.ini

Piggyback on #643 
Leftover header and not-yet-implemented terminal command.

Fixing build for #643

---

code/espurna/config/general.h
code/espurna/debug.ino
code/espurna/ws.ino
code/html/custom.css
code/html/custom.js
code/html/index.html

My stab at building a web console, in reference to #650 
I agree it's ugly - feel free to change the visuals, especially alignment. 
Looking at Status page, it would be good if it was 2 columned layout in Desktop, and single columned (like now) in mobile versions.

Debug console on web

---

code/html/custom.js

* replaced `is(":checked")` with `prop("checked")`
* replaced `$(":checkbox")` with native selector
* change `showPanel` to resize checkboxes only in active view.
* same for scheduler **Enabled** checkbox

WebUI checkboxes improvements

---

code/espurna/config/arduino.h
code/espurna/config/hardware.h
code/espurna/migrate.ino
code/platformio.ini

support for tunbox powerstrip02

support for tunbox powerstrip02

---

code/platformio.ini

Update platformio.ini typo

---

code/espurna/config/hardware.h

set KMC HLW8012 upstream voltage resistor to 2 * 1M

set KMC HLW8012 upstream voltage resistor

---

code/espurna/scheduler.ino
code/html/custom.js

Apparently JS makes a difference between 1 and "1"

Make switch schedules work again

---

code/espurna/config/arduino.h
code/espurna/config/hardware.h
code/espurna/config/prototypes.h
code/espurna/config/sensors.h
code/espurna/i2c.ino
code/espurna/migrate.ino
code/espurna/sensor.ino
code/espurna/sensors/AM2320Sensor.h
code/espurna/sensors/GUVAS12SDSensor.h
code/espurna/sensors/I2CSensor.h
code/espurna/sensors/SI7021Sensor.h
code/espurna/utils.ino
code/html/custom.js
code/platformio.ini

new devices&sensors + some fixes

new devices&sensors + some fixes

---

code/espurna/config/hardware.h
code/platformio.ini

Adds support for 4+1 Power Strip ZLD-44EW-W based on TYWE2S
details in https://github.com/wildwiz/espurna/wiki/Zhilde-ZLD-44EU-W-Installing-Espurna

Support for Power strip Zhilde ZLZ-44EW-W

---

code/espurna/config/general.h
code/espurna/config/types.h
code/espurna/ir.ino

added IR_BUTTON_MODE_TOGGLE to ir.ino and added a supporting remote to demonstrate toggle mode for 8CH relays

Added IR Toggle Mode 

---

code/espurna/ir.ino

some remotes repeat the code within 200ms thus toggling the relay twice , this fixes the toggle function.

Fixed multiple toggles due to repeated code

---

code/espurna/config/arduino.h
code/espurna/config/hardware.h
code/espurna/migrate.ino
code/platformio.ini

Fixes issue: Support for Itead Sonoff Pow R2 #761

Initial support for Itead Sonoff POW R2

---

code/espurna/config/hardware.h
code/platformio.ini

This is a smart wall switch board, featuring 2x 5A mains SPST channels and 2x mains inputs (so it is suitable to replace two pulse relais)
more info on 
https://luani.de/projekte/esp8266-hvio/
https://luani.de/blog/esp8266-230v-io-modul/

support for luani HVIO https://luani.de/projekte/esp8266-hvio

---

code/espurna/config/arduino.h
code/espurna/config/hardware.h
code/espurna/migrate.ino
code/platformio.ini

For details about the board see http://www.allnet.de/de/allnet-brand/produkte/neuheiten/p/allnet-4duino-iot-wlan-relais-unterputz-esp8266-up-relais/

Add support for Allnet ESP8266_UP_Relay

---

code/espurna/homeassistant.ino

Remove quotes from HomeAssistant units

---

code/espurna/relay.ino

Adding the relay delay feature also to none GPIO (pin mode relays).

Allow RELAYx_DELAY_ON/OFF also for none GPIO relay types

---

code/platformio.ini

fix some extra_script typos: missing curly bracket & duplicate.

fixed some extra_script typos

---

code/espurna/config/hardware.h
code/platformio.ini

Also, switch to more recent platform. Use common.platform_XXX syntax

Cover more modules with travis

---

.travis.yml
code/build.sh

Make travis run in parallel. 
Minor improvement for dev branch, but major for full releases. 
Based on months-old work by @mcspr and myself.

Travis parallel builds

---

code/gulpfile.js

Use system dependent directory separator instead of hard coding / which doesn't work on window.

Using correct separator

---

code/espurna/utils.ino
code/html/index.html

Resolves #1023 
Show revision in terminal and web.
#1008 added APP_REVISION as build flag for build.sh builds

Show APP_REVISION value in terminal and web

---

code/platformio.ini

This Module has an ESP-07 on it with only 1MB Flash!

Update Luani Module to 1MB Flash

---

code/espurna/ota.ino

no duplicate messages while OTA Update throug PlatformIO or Arduino IDE

OTA Progress Debug Msg only on change

---

code/espurna/config/hardware.h
code/platformio.ini

Added Homecube 16A Wifi socket with RGB LED ring
See #1105

Added Homecube 16A

---

code/espurna/sensor.ino

I kept getting this file modified after saving as the editor strips whitespaces automatically.

Remove extra whitespace from sensor.ino

---

code/espurna/config/sensors.h

Fix _INTERRUPT_MODE comment

---

code/espurna/config/hardware.h
code/platformio.ini

It seems to be very similar to the ITead Sonoff B1, so it's based on that.
This should be the official product page if I'm not mistaken:
http://www.lohasled.com/9w-a19-p00064p1.html

Add support for Lohas 9W bulbs

---

code/platformio.ini

Fix platformio env shelly1 typo

---

README.md

Added Teckin as a supported device. The model I have is an [SP22](https://www.amazon.de/TECKIN-Steckdose-Intelligente-fernbedienbar-funktioniert/dp/B07CDCYLQ6) (not sure if there are other models).
Question: How is best to document these other "brands" to help indexing in google et al?

Added Teckin as supported device

---

.github/stale.yml

https://github.com/xoseperez/espurna/commit/be0d7593af8baf6b834d089298b937c54be32124#diff-0582c54ce27332bb1bf68e65f7b91d0d did change config but did not update what stalebot says
*edit: yay codacy works*

Update stale.yaml comments

---

code/espurna/config/sensors.h
code/espurna/config/types.h
code/espurna/sensor.ino
code/espurna/sensors/SDS011Sensor.h

i added support for the SDS011 sensor. It can measure P2.5 and P10 particulates.
Basically i cloned MHZ-19 and put code from https://github.com/ricki-z/SDS011 onto it.

added SDS011 sensor support

---

code/espurna/telnet.ino

delete client object before setting pointer to null

Fix memory leak in telnet module

---

code/espurna/rfm69.ino

"Clear counts" on rfm69 does not reset node count properly.

-Fix for issue #1239 

---

.travis.yml

Use && to properly set exit code

Fix travis not failing on npm-ci

---

code/espurna/ir.ino

Move _ir_results checks to non raw part.
Add _ir_results.rawlen check to raw part.

fix _ir_results checks for Raw mode

---

code/espurna/ir.ino

Change var type to unsigned int in for loops.
Change _ir_code to str conversion (thanks hos500)
https://github.com/xoseperez/espurna/issues/1302

Fix compiler warnings, fix str to ul convert

---

code/espurna/api.ino

Resolve #1280 
Resolve #1299 
...and #1294?
*thoughts: maybe registerReload should just call the cb right away?*

Add missing initial configuration for HTTP API

---

code/espurna/config/general.h

fix for: we should send only buttons events that have actions assigned to them or set BUTTON_MQTT_SEND_ALL_EVENTS to 1 to send everything

fix for commit 30285b3

---

code/espurna/config/general.h

Overrides in ```custom.h``` do not otherwise work.

allow override of HA settings and WEB_REMOTE_DOMAIN

---

code/espurna/sensor.ino
code/espurna/sensors/PZEM004TSensor.h

I updated some log messages and added a diagram regarding the connection of multiple pzem devices.
I also have 2 images that need to be uploaded to Wiki. How to do it? I don't have permission to commit on Wiki.

Updated PZEM004T documentation and small fixes

---

code/espurna/rfbridge.ino

Proper buffer size to fit two digit rfbOFF key

---

code/espurna/config/general.h
code/espurna/telnet.ino
code/html/index.html

settings / webui key `telnetAuth`, akin `wsAuth`
logic is always included in the build, exception for `espurna-core-...` (like the station setting)

Telnet password setting

---

code/espurna/nofuss.ino

[Fix] Disabling EEPROM Rotate before updating upgrading firmware with

---

code/html/index.html

NoFUSS panel

---

code/espurna/rf.ino

This fixes a bug in saving RF codes set in the UI/websocket.

Fix RF code conversion to long

---

code/espurna/rfbridge.ino

Missed this one when API_SUPPORT is enabled as well.

Fix compile error when both RF_SUPPORT and API_SUPPORT are enabled

---

code/espurna/alexa.ino

Use built-in fauxmoESP HTTP handler when WEB_SUPPORT=0

---

code/espurna/relay.ino

Make pulse working for dummy/virtual relays

Fix pulse for dummy relays

---

code/espurna/sensors/PMSX003Sensor.h

Support PMS5003S sensor ([data sheet](https://lcsc.com/product-detail/Sensor-Modules_Beijing-Plantower-PMS5003S_C91432.html))

Support PMS5003S

---

code/memanalyzer.py
code/ota.py
pre-commit

Hey there,
I was just reading through the code and cleaned up the Python code.   Nothing functionally should change.   I've put some comments in the PR to explain the motivation behind some changes.  I feel they make the code more obvious

Python cleanup

---

code/espurna/domoticz.ino

Fixes #1264 
Simply sync the last sent state with the real relay status.
`std::vector<bool>` can also be `std::bitset` to be more clearer about the intent.
Part of a quite larger rewrite, but the domoticz change is small enough to push already without changing broker too:
https://github.com/xoseperez/espurna/compare/dev...mcspr:broker/events?expand=1#diff-293f13e357a370069b4aa129f14363a6

Domoticz: track last relay state

---

code/espurna/config/arduino.h
code/espurna/config/hardware.h
code/espurna/migrate.ino
code/platformio.ini

Added initial support for Oukitel Smart Switch. This is a 2 outlet plug
that has the same ESP8266 pinout as the YiDian XS-SSA05.

ADDED SUPPORT FOR OUKITEL P1 SMART SWITCH

---

code/espurna/domoticz.ino

fixup #1536 so it actually sends state on connection

Only check domoticz state in broker callback

---

code/espurna/mqtt.ino

fix #1560 
do not trust mqtt client to actually connect, lock when connecting and wait until unlocked

Wait until mqtt client has finished trying to connect

---

code/espurna/alexa.ino
code/espurna/api.ino
code/espurna/button.ino
code/espurna/debug.ino
code/espurna/domoticz.ino
code/espurna/espurna.ino
code/espurna/ir.ino
code/espurna/led.ino
code/espurna/libs/RFM69Wrap.h
code/espurna/libs/StreamInjector.h
code/espurna/light.ino
code/espurna/migrate.ino
code/espurna/mqtt.ino
code/espurna/nofuss.ino
code/espurna/ntp.ino
code/espurna/ota.ino
code/espurna/relay.ino
code/espurna/rfbridge.ino
code/espurna/sensor.ino
code/espurna/web.ino
code/espurna/wifi.ino
code/espurna/ws.ino
code/gulpfile.js
code/html/index.html

[copyright-update] Update for 2019

---

code/espurna/system.ino
code/espurna/utils.ino
code/espurna/wifi.ino

- revert compile-time checks from https://github.com/xoseperez/espurna/commit/31195ba3b62ff886313d0369baf4b6ab1a07187b
- runtime settings for sleep mode
Something to test #1574 
My observations with Basic - nothing WiFi works unless loopDelay > 0

Set wifi sleep mode from settings

---

code/espurna/config/sensors.h

This patch provides better documentation of BMX280 oversampling settings.

Better documentation of BMX280 settings

---

code/espurna/light.ino

fixup 868d153f lights status refactor

Send brightness to websocket

---

code/espurna/config/hardware.h

Mine was not working till I added BUTTON_SET_PULLUP | BUTTON_DEFAULT_HIGH.
Not sure if both are needed.

update hardware.h GREEN_ESP8266RELAY button1 mode

---

code/espurna/mqtt.ino

See: https://github.com/xoseperez/espurna/pull/1645#issuecomment-477217797

Fix building without MQTT_SUPPORT

---

code/espurna/sensors/CSE7766Sensor.h

https://gitter.im/tinkerman-cat/espurna?at=5c9d3f735349305a4c865ed7
tnx to @lipoforall

Fix CSE7766 magnitude count

---

code/espurna/config/sensors.h

default pins (#1646)
add define to SENSOR_SUPPORT

MAX6675: default pins and SENSOR_SUPPORT dependency

---

code/espurna/mqtt.ino

https://github.com/xoseperez/espurna/issues/1465#issuecomment-484566975

MQTT: Reset connection timer with PubSubClient

---

README.md
code/platformio.ini

Removed in favour of BW-SHPX bin
https://travis-ci.org/mcspr/espurna-nightly-builder/jobs/519095501#L987
https://github.com/xoseperez/espurna/commit/1f2577a4ef41ff06a1bb995476af1d499e6b68fc#diff-64ccb24d1cc0509f64794258b04da3ecL2881

Remove gosund-sp1-v23 env

---

code/espurna/led.ino

LED: store default settings exactly once

---

code/espurna/light.ino

I forgot to send mired via MQTT in #1732.

MQTT: send mired if cct in use

---

code/espurna/mqtt.ino

- display connection state in terminal
- reset connecting flag. probably harmless though

MQTT connection state

---

.gitattributes
code/platformio.ini

https://travis-ci.org/mcspr/espurna-nightly-builder/jobs/541572533#L721
https://travis-ci.org/mcspr/espurna-nightly-builder/jobs/541572534#L720
Fix -D... params in build flags
Make env names the same as definitions

Fix PSH environments

---

code/espurna/wifi.ino

https://gitter.im/tinkerman-cat/espurna?at=5d0e643a5bc3210bb77cf77c

Let JustWifi fallback handle AP

---

code/espurna/relay.ino

ref https://github.com/xoseperez/espurna/issues/1530

Relays: drop legacy settings migration

---

code/espurna/espurna.ino

https://github.com/xoseperez/espurna/commit/08a748e05d356209963aadb2768d19e0a40d9713#commitcomment-34131336

DEBUG_SUPPORT check for crashSetup

---

code/espurna/config/hardware.h

Reverts xoseperez/espurna#1779

Revert "Fix LED Invert for YJZK Switches"

---

code/extra_scripts.py
code/platformio.ini

https://github.com/xoseperez/espurna/pull/1805#issuecomment-508763013
- bump platforms
- directly get framework dir instead of using env variable
- reference development platforms

PIO: Update for recent platforms

---

code/espurna/config/general.h
code/espurna/config/hardware.h
code/espurna/wifi.ino

Make compilation more flexible allowing to define in custom.h your own variation to devices and define four WiFi networks.
The only change in hardware.h is:
#if not defined(MANUFACTURER)
// -----------------------------------------------------------------------------
// ESPurna Core
// -----------------------------------------------------------------------------
...
#endif
// -----------------------------------------------------------------------------
// Check definitions
// -----------------------------------------------------------------------------
...

Make compilation more flexible

---

code/espurna/config/hardware.h
code/platformio.ini

Adding support for a new device. Tested on a device and basic functionality works ok.

 * Added support for Etekcity ESW01-USA device

---

code/espurna/config/general.h
code/espurna/config/prototypes.h
code/espurna/domoticz.ino

resolve https://github.com/xoseperez/espurna/issues/1763
- simply apply channel values. maybe we do need to use temperature at some point, but it seems those are updated too
- fix lights constants from the #1874

Domoticz: handle cmode=2

---

code/espurna/ws.ino

https://github.com/xoseperez/espurna/issues/1845#issuecomment-527147468
>  the web admin page does not always refresh on change of status (ie on/off)

WS: check for client_id value before checking for client

---

code/espurna/relay.ino

resolve https://github.com/mcspr/espurna-nightly-builder/issues/6
fixed swapped on & off, overlooked param warning and default toggle string

Relay: fix typos in payload configuration

---

code/espurna/wifi.ino

- use getSetting(key, index, default), slightly less code size
- place WIFI1..., WIFI2.... strings into flash. F() aka FlashStringHelper is automatically accepted via String constructor
- `#include <JustWifi.h>`

WiFi settings clean-up

---

code/espurna/homeassistant.ino

As it is provided via mqtt anyways

Add color temperature state to homeasssistant config generation

---

code/espurna/config/general.h
code/espurna/wifi.ino

WiFi: configure tx power

---

code/espurna/telnet.ino

Get rid of _telnetFirst (assumption that first line is always telnet renegotiation)
Discussed in: https://github.com/xoseperez/espurna/pull/1920#issuecomment-535579529

Properly handle telnet renegotiation

---

code/espurna/config/arduino.h
code/espurna/config/hardware.h
code/platformio.ini

Control board for **Hoermann UAP1** Garage interface
http://frank-schuetz.de/index.php/fhem/13-hoermann-torantrieb-mit-espeasy-in-fhem-einbinden

FS-UAP1 Adding support for ESP8266 FS-UAP1 Control board

---

code/espurna/button.ino
code/espurna/wifi.ino

https://gitter.im/tinkerman-cat/espurna?at=5da0580639d0c707578ddb5c

WiFi: toggle STA mode back to avoid softlock

---

README.md

- reference releases/latest for master branch
- add vscode and arduinoide pages
- reword nightly notice, add build info before it

Fix releases URLs and add more info about compilation

---

README.md
code/espurna/config/deprecated.h

Update readme and accumulated deprecated.h comments

1.13.6 -> 1.14.0

---

code/espurna/gpio.ino

See also: https://github.com/xoseperez/espurna/commit/01345987cd71965675972af0b386fbd8f26166ff#commitcomment-35862859

Fix exception on bitset.test

---

code/espurna/config/general.h
code/espurna/utils.ino

- treat the first bit in hbReport as enable-all flag
- add bssid topic, fix #1990

utils/heartbeat: fix hbReport=1 condition, add Bssid

---

code/espurna/utils.ino

THERMOSTAT_SUPPORT=1 should build: https://github.com/xoseperez/espurna/commit/ca56e0e4c1b3892df42ac4bd7fb14f8dea4dc668

Fix heartbeat check for thermostat, add Bssid for influx

---

code/espurna/relay.h
code/espurna/relay.ino

relay: compare sum of physical + dummy relays instead of just dummy

---

code/platformio.ini

This adds core 2.6.1 and updates the core 2.5.2 release

Update Arduino core in PIO

---

code/platformio.ini

- add nodemcu-lolin-secure-client
- add nodemcu-lolin-latest based on $platform_latest
- remove nodemcu-lolin-252 based on $arduino_core_2_5_2

Update nodemcu-lolin envs

---

code/espurna/api.ino
code/espurna/button.ino
code/espurna/config/prototypes.h
code/espurna/espurna.ino
code/espurna/mqtt.ino
code/espurna/nofuss.ino
code/espurna/ota_arduinoota.ino
code/espurna/ota_asynctcp.ino
code/espurna/ota_httpupdate.ino
code/espurna/system.h
code/espurna/system.ino
code/espurna/terminal.ino
code/espurna/web.ino
code/espurna/ws.ino

- add nofuss custom reset reason
- nice_delay instead of ticker for arduinoota success callback, since the library will reset the board immediately after the callback returns
- move system.ino prototypes into system.h, alias cb type
- naming change for system rtcmem

OTA and system callbacks adjustments

---

code/espurna/domoticz.ino

domoticz: proper datastructure for mask

---

.travis.yml

-> https://travis-ci.org/xoseperez/espurna/builds/618791096 
- Fix stage names,
- Don't run test stage on tagged commits
(since release commit was already tested via PR or branch test beforehand)

travis: fix stages

---

code/espurna/ir.ino

This reverts commit 7efaaa8a8054cb4cb3c421ca92a0d98f39922b32.
https://gitter.im/tinkerman-cat/espurna?at=5df6944dac14cc652c8c8e91

Revert "ir: use proper methods"

---

code/platformio.ini

Changelog: https://github.com/esp8266/Arduino/releases/tag/2.6.3

Update Arduino core to 2.3.2

---

code/espurna/config/hardware.h

Fix SHP8, thanks to @RDobrinov 
https://gitter.im/tinkerman-cat/espurna?at=5df8a3a20dc628523e4de80c

Hardware: set button pull-up on shpx-v23 boards

---

code/espurna/homeassistant.ino
code/html/index.html

...by disabling it when HA MQTT discovery is enabled.
Also as-fat-as-possible warning under useCSS toggle

HA: try to avoid conflict with useCSS

---

code/espurna/config/arduino.h
code/espurna/config/hardware.h
code/platformio.ini

This is a 13W RGBWW smart bulb sold on Amazon: https://www.amazon.de/Gl%C3%BChbirnen-TECKIN-Lampenbirne-Kompatibel-Zeitgesteuerte/dp/B07RR1BYF7

Add support for Teckin SB53 smart bulb
