- code/espurna/config/general.h
- code/espurna/config/hardware.h
- code/espurna/relay.ino
- code/platformio.ini
Hi
This pull request adds support for generic board which is based on esp-01 module and stm8s103 microcontroller.
Microcontroller is connected to esp8266 by serial port and is listening for commands to turn on and off relays.
Here is the link to the module:
https://www.aliexpress.com/item/5V-ESP8266-ESP-01-2-Channel-WiFi-Relay-Module-2-Channel-Relay-Module-For-IOT-Smart/32843970608.html
The buttons on board are inaccessible - they are connected to the stm8s103, and are used to restore/reset settings when using ESP-01 with Ai-Thinker firmware, they just send some AT+RST, AT+RESTORE commands when being hold.
The firmware in stm8s103 takes few seconds to start, and doesn't allow sending commands one after another - 8c629ba7ab1e0a915f230a40d730769270379b7b - this fixes the state of relays …
> support board with 2 relays and stm8s103

- README.md
Use upstream firmware that includes the fork link included.
> Use upstream firmware that includes the fork

- code/espurna/config/general.h
- code/espurna/system.ino
- code/espurna/utils.ino
- code/espurna/ws.ino
- code/html/index.html
Calculate poor-mans load average of CPU utilization and display it on status page and MQTT telemetrics. 
Credits for idea go to ESPEasy team.
Useful for understanding if there's some polling that's holding up the CPU (like sync sensors reading or similar).
> Load average

- .travis.yml
- code/espurna/config/hardware.h
- code/platformio.ini
This is in ref to #636 and having slimmer builds for `dev` branch. 
So, instead of doing full `./build.sh` with all 50+ images, I created one (and can add more) dummy images that build with as much code as it's possible. This way, build coverage is high (or even higher than usual) with just few images. 
Build times should be significantly shorter for `dev` while you can still set full build for master branch. 
You can also explore TravisCI "cron" option to still do a periodic full build on `dev`, but just not after each commit.
> Add dummy image that would compile in a lot of functionality.

- .travis.yml
Since there's already logic to determine travis builds in build.sh, no need to explicitly pass the list of builds in .travis.yaml
> logic for determining travis builds is already in build.sh

- code/espurna/config/hardware.h
- code/platformio.ini
Added 2 more travis builds (though, almost empty) to test for: 
- Additional relay types (Light, dual and My92xx) 
- DHT
- My9231 light type
- SSL 
`travis02` and `travis03` image leave a lot room (pins) for additional sensor options and 3 images should still be faster than 50 :)
> Additional Travis build coverage 

- code/.gitignore
- code/espurna/config/general.h
My kid loves to play with this switch ( turn on and off a lot) and sometimes it reaches the max unstable count so I need increase that number at build time.
> Export max system check for build configuration

- code/espurna/button.ino
- code/espurna/mqtt.ino
If you set "MQTT Retain" to on, than all values are retained and kept for later.
While this is good for things that have state (relays, switches), it's not necessary good for pushbuttons which are fire-and-forget.
To make sure buttons are sent wihtout retain flag, regardless of general settings, I had to monkey around with few overloads of `mqttSend()` and `mqttSendRaw()`, so hopefully I didn't break anything.
@xoseperez  - counting you will double check before merging.
> Buttons should not retain in MQTT

- code/espurna/homeassistant.ino
- code/html/index.html
One of the HASS Units is a % which needs to be quoted or Home Assistant rejects the config.  No harm in quoting the others as well.
> Fix some typos in the Hass info

- code/espurna/config/general.h
- code/espurna/utils.ino
On a par with information provided by mDNS, telnet and web. Can be useful to know for OTA, as device can be unreachable with telnet/web or be on separate network.
> Add 'board' to the MQTT heartbeat

- code/espurna/debug.ino
- code/html/custom.css
- code/html/custom.js
- code/html/index.html
I noticed that 04cdb22 escapes some chars for the weblog.
This way client handles the escaping through jquery `text` (which is a wrapper for `textContent` attribute) and esp doesn't waste time rebuilding the string, as there are also `&lt;`,`&gt;` etc.
```javascript
> var test = $("<li></li>").text("<div>{escapeme}</div>");
> test.children().length
0
> test.text()
"<div>{escapeme}</div>"
```
> Escape html for weblog in the client

- code/html/custom.css
- code/html/index.html
It says that `div .header > h1` inherits line-height value of 1.6em from .content class. And it looks like this in portrait mode:
> Resize WebUI elements for narrow screen

- code/espurna/config/defaults.h
- code/espurna/espurna.ino
- code/espurna/mqtt.ino
- code/espurna/utils.ino
Crude solution to #732 
- Actually show current settings in MQTT panel
- For hostname, first try to use HOSTNAME #define and only then generate it via getIdentifier
> Missing values in MQTT configuration, hostname define.

- code/espurna/config/sensors.h
CSE7766 was left probably by mistake enabled by default. This caused garbage in the serial while monitoring.
> Disable CSE7766 by default

- code/espurna/light.ino
I've noticed the inputValue can get out-of-sync if the user switch between `_light_use_white` true and false. The out-of-sync value would be saved on reboot and is therefor also persistent. And MQTT light would always send wrong data for this channel.
> Always set white inputValue to 0

- code/build.sh
Fix build script to exit with non 0 on failure. 
This should give us more accurate travis builds.
> build process should exit with non 0 value on failure.

- code/html/custom.js
- code/html/index.html
Before looking into separate urls for menu I wanted to fix this interaction with menu button on mobile.
- Remove `#menu` from menu button href
Going to web page on mobile and pressing menu button once locks url with `#menu`
Refreshing without pressing any menu item or just pressing menu again breaks `connect()` - websocket tries to open `ws://<ip>/menuws`
- Using URL API to get `/config`, `/ws` and `/upgrade` urls
Just to be safe
`new URL()` already skips hash from inherited root and is easier to read than string manipulation.
> WebUI url parsing

- README.md
- pre-commit
I was looking into extending extra_scripts.py to have git related functions. For example, to add APP_REVISION using -DAPP_REVISION=... or replace PROGNAME of firmware to have git short commit and tag. Starting with this as it also uses that info. Will properly extract them later.
- Fixed cwd assumptions, pre-commit always starts at the repo base
- Extract USER and REPO from "origin" url directly
- Refactored into separate functions and \_\_main\_\_
- pre-commit can now be symlinked into .git/hooks, not only copied. This happened before:
```bash
$ git commit
Traceback (most recent call last):
File ".git/hooks/pre-commit", line 39, in <module>
VERSION = getVersion()
File ".git/hooks/pre-commit", line 33, in getVersion
lines = open(file_name).readlines()
IOError: [Errno 2] No such file or …
```
> Reworked git pre-commit hook

- code/espurna/sensors/PMSX003Sensor.h
- code/platformio.ini
1. Support PMS5003T/PMS5003ST;
2. Rewrite data reading method;
3. Remove PMS library dependency (move control command into espurna);
4. Support smart sleeping mode to extend the sensor’s lifetime.
Tested successfully for PMS5003T and PMS5003ST sensor in NodeMCU. Imagine working on other PMSX003 devices as well.
Need help: I use MAGNITUDE_ANALOG for HCHO, since I don't known how to rebuild compressed web package. Could you please add HCHO MAGNITUDE support in custom.js, Thank you.
> Refine PMSX003 to support PMS5003T/PMS5003ST.

- code/espurna/config/hardware.h
- code/espurna/rfbridge.ino
- code/platformio.ini
Replaces pull request https://github.com/xoseperez/espurna/pull/795
Rebased on dev, and squashed commits
This patch enables the hardware modifications for Sonoff RF bridge describted in https://github.com/wildwiz/espurna/wiki/Sonoff-RF-Bridge-Enchanced-RC-Recognition, which bypass entirely the hardware RC recognition performed by RF bridge auxiliary microcontroller and offloads the task to the ESP8266.
As already mentioned in https://github.com/xoseperez/espurna/pull/795, this patch replaces source/dest of RF TX/RX data preserving all the other features of original Espurna implementation for Sonoff RF bridge (including learning, mqtt interactions and transmitting commands over RF).
> RFB_DIRECT sonoff bridge hardware bypass of the RF microcontroller

- code/espurna/config/progmem.h
- code/espurna/config/sensors.h
- code/espurna/sensor.ino
- code/espurna/sensors/PMSX003Sensor.h
1. Set PMS sensor type dynamically;
2. Refine unit of hcho/temperature/ugm3.
Tested successfully on PMS5003T
> Set PMS sensor type dynamically

- code/platformio.ini
itead-sonoff-rfbridge-direct-ota, itead-sonoff-s31-ota and zhilde-eu44-w-ota were still pointing to the hardcoded 192.168.4.1/fibonacci target, moved them to use the environment variables.
> removing hardcoded ota settings still in some platformio environments

- code/espurna/telnet.ino
Looking at wireshark data, telnet sometimes sends 'ff ec' (xEOF) in sequence multiple times. And without close(true) this trigged watchdog reboot.
> Ctrl-d for telnet

- code/espurna/homeassistant.ino
Turns out "sensor" value was just silently ignored as sensor.mqtt did not support it. Current version (0.69.1) throws exceptions about it
https://www.home-assistant.io/components/sensor.mqtt/#device_class
https://www.home-assistant.io/components/sensor/#device-class
> Don't send device_class for Home Assistant sensor

- code/espurna/config/defaults.h
- code/espurna/utils.ino
From #880, #874 - use hyphen instead of underscore
> Do not use underscore in SSID / hostname

- code/espurna/migrate.ino
- code/espurna/mqtt.ino
It is marked as deprecated since 1.12.2
Maybe do this instead?
> Migrate from {identifier} to {hostname}

- .gitignore
- code/espurna/rfbridge.ino
Hi, this patch responds to the issue raised in #885 (rf bridge and energenie remotes) being able to receive but not to transmit codes from the rf bridge.
In the initial implementation I suppressed the timing information from rc-switch output in order to emit consistent RC codes (if timing varies from one key stroke to the other, the consumer the other side of MQTT would have a hard time to recognize the varying code. 
The varying time in RC codes is an issue also in the 'vanilla' rf-bridge implementation, as signaled also in #910 (Controlling rf433 bridge via MQTT broker)
The changes I have made for the -direct firmware address these points.
* Embed timing information in received codes from received RF
* Use embedded timing information, if available, transmitting to RF  
(if timing is not …
> sonoff rf bridge, handling of variable protocol speeds

- code/espurna/api.ino
- code/espurna/homeassistant.ino
- code/espurna/mqtt.ino
- code/espurna/web.ino
- code/espurna/ws.ino
Solving heap problems from #896. Limited testng prefilling eeprom with bunch of "a"*64 strings and accessing /config when websocket is active.
For example, _onGetConfig method when settings size is `3236/4096`
|state|getFreeHeap()|jsonBuffer.size()|
|---|---|---|
|initial|22512|40|
|after settingsGetJson()|14768|4370|
|after printTo()|12528|4370|
|after clear()|20544|0|
> Free jsonBuffer after printing

- code/extra_scripts.py
SCons does not think firmware.bin exists on first build, the size is 0. Just get the path and use python method.
Re-enable back OTA size warning for 1MB boards and show it through stderr to circumvent being hidden when pio is ran with --silent
idk about 512000 though (numbers below from ldscript sizes 1m0m1s and 1m0m2s)
should it be ((999 * 1024) / 2) == 511488.0?
or maybe ((995 * 1024 / 2) == 509440.0?
> Show true binary size and warning in check_size

- code/html/custom.css
- code/html/custom.js
Resolve #1028 (nvm commit in the issue, used webui and forgot how it works. forcepushed over it later)
Safari only supports clip-path with `-webkit-` prefix: https://caniuse.com/#feat=css-clip-path
I assume `clipPath` === `clip-path` and hyphen-less css property is just <s>jquery</s>js magic camelCase conversion. Still works with hyphen
> Safari needs -webkit- prefix for clip-path

- .travis.yml
- code/build.sh
- Revert test to being serial. Releases are using parallel jobs.
- Some cosmetic changes in build.sh
Matrix expansion is somehow slower? I did watch #986 merge build, 10 minutes per 10 minutes total. Which is strange, bc jobs did not start parallel at all.
> Separate test and release stages in travis

- .travis.yml
- code/build.sh
- code/espurna/config/version.h
- separate statements instead of inline logic
- `-DAPP_REVISION=...` instead of modifying file (see accidental commit of version.h)
- show revision in the log (git describe shows current tag or `<tag>-<n-commits>-<sha1>`)
- set -e to avoid some issues when commands fail in build.sh but build succedes
- check for git command presence, because with `set -e` it will fail without it. source.tar.gz downloaded from releases should still work
Requires #1007
> build.sh rework

- .travis.yml
Travis pulls tag as branch, so branch === tag.
Use same regexp as earlier build.sh did, matching ^ MAJOR dot MINOR dot PATCH $
Sorry, only noticed it yesterday tweaking nightlies conditions with [this at the top for tagged builds](https://travis-ci.org/mcspr/espurna-travis-test/builds/401542380#L407):
> git clone --depth=50 --branch=20180708 https://github.com/mcspr/espurna-travis-test.git mcspr/espurna-travis-test
> Hotfix travis release condition

- code/html/custom.js
> Don't show alert on already set hostname

- code/espurna/config/hardware.h
When "LED Mode" = "Relay Status", KMC 70011 led was off when relay was on. Fixes by inverting led.
> invert led on kmc 70011

- code/espurna/config/hardware.h
`LED_MODE_*` defines were moved from `general.h` to `types.h`
> update hardware.h doc comment about LED_MODE

- code/html/custom.css
- code/html/custom.js
- code/html/index.html
changed the look and feel of the checkboxes to resolve Edge issue + brought disabled state for them
also minor html fixes
ON OFF switch in Microsoft Edge #1049
> [fix]ON OFF switch in Microsoft Edge #1049

- code/build.sh
* avoid silent errors with git detection. `command -v git` had no 'else' thus exit code bubbled up.
* actually check for $par_build. [ $par_build ] checks for string length >0 and not for value, which is satisfied by setting it to zero earlier and thus always true.
* `git-describe` will break on shallow clone. Namely travis does this, `fatal: No names found, cannot describe anything.` will happen if there are >50 commits since last fetched one (or where i got this is cloning repo with --depth=1 and trying to use build script). can tweak depth, but since it is just used as a nice banner switch to version+revision, as version is already known from the header and not really related to tag value.
> Fix up build.sh error handling

- code/build.sh
- code/platformio.ini
* `env:pilotak-esp-din-v1` got caught by `ota` grep and left out of releases
* `env:itead-sonoff-dual-r2-ota` had -r2 and -ota swapped
* switch to egrep syntax and filter envs more strictly
> Improve build.sh -ota envs detection

- code/espurna/led.ino
> espurna/code/espurna/led.ino:296:8: warning: extra tokens at end of #endif directive [enabled by default]
> #endif LED_SUPPORT
> ^
sidenote: ...i think projenv on extra_script side *can* enable warnings just for project. need to check this...
> Minor comment error in led.ino

- code/espurna/config/arduino.h
- code/espurna/config/hardware.h
- code/platformio.ini
I don't know if this is actually required since espurna already has the `wemos-d1mini-relayshield` environment but since I don't operate my wemos with this shield, I thought it could be helpful for others to have this one available as well.
> Add support for wemos-d1mini dev board

- code/extra_scripts.py
For example, setting `PLATFORMIO_BUILD_FLAGS=-DRELAY1_PIN=13` and then building `nodemcu-lolin` will not override default `RELAY1_PIN=12` from hardware.h and compiler is quiet about it. This warning, inhibited by -w, would be helpful:
> In file included from espurna/config/all.h:29:0,
> from /home/builder/espurna/code/espurna/espurna.ino:22:
> espurna/config/hardware.h:76:0: warning: "RELAY1_PIN" redefined [enabled by default]
> #define RELAY1_PIN          12
> ^
> <command-line>:0:0: note: this is the location of the previous definition
See [travis02](https://travis-ci.org/xoseperez/espurna/jobs/412021410) and [travis03](https://travis-ci.org/xoseperez/espurna/jobs/412021411) build logs.
> Turn off warnings only for external code

- code/espurna/config/arduino.h
- code/espurna/config/hardware.h
- code/espurna/config/progmem.h
- code/espurna/config/sensors.h
- code/espurna/config/types.h
- code/espurna/sensor.ino
- code/espurna/sensors/SonarSensor.h
- code/html/custom.js
- code/platformio.ini
* Works with many different ultrasonic sensor models: HC-SR04, SRF05,  SRF06, DYP-ME007, JSN-SR04T & Parallax PING)))™.
* Built-in digital filter method ping_median() for easy error correction (use `SONAR_ITERATIONS` build flag to configure).
* Allows setting of a maximum distance where pings beyond that distance are read as no ping or clear (use `SONAR_MAX_DISTANCE` build flag).
> Add support for NewPing

- code/espurna/config/sensors.h
- code/espurna/sensor.ino
- code/espurna/sensors/PMSX003Sensor.h
Another option for connecting PMSX003 devices using just GPIO3 (RX).
> Add support for hardware serial on PMSX003 devices

- code/espurna/sensors/PMSX003Sensor.h
I actually think all `PMS_` variables should be renamed to `PMSX003_` otherwise there is `PMSX003_SUPPORT` and then everything else is just `PMS_`.
> Fix incorrect PMS_SUPPORT reference on sensor endif

- code/espurna/config/arduino.h
- code/espurna/config/hardware.h
- code/espurna/migrate.ino
Support for the new Shelly1 relay.
Official page: https://shelly.cloud/product/shelly-1-open-source/
Docs: http://shelly-api-docs.shelly.cloud/#shelly1-relay-index
> add support for shelly1 relay

- code/html/index.html
In web gui wifi settings, leaving wifi ip field empty will result DHCP negotiation (not DNS...)
> Fix typo in hint text

- code/html/custom.js
two bugs in one, closely related
'processData' called 'resetOriginals' every ws message, which resulted in zeroing numReboot/numReload/numReconnect and changing 'original' to user-edited value at random intervals.
i assume 'haschanged' was intended to track 'original' value until it is saved. but it only did so the first time input was edited, because attr() returns text and === comparison with integer fails on both branches.
> Really track changed input in WebUI

- code/espurna/sensors/PMSX003Sensor.h
Call wakeUp PMS on first reading cycle to avoid not data in a long period (e.g. PMS entered sleeping and then espurna reboot, we should wake up PMS right now)
> WakeUp PMSX003 sensor on first reading cycle

- code/espurna/config/all.h
- code/espurna/config/prototypes.h
- code/espurna/utils.ino
- code/platformio.ini
https://github.com/xoseperez/espurna/commit/88e2eccccef3846845c2b43d5b58e3a24c61ef2d#diff-bd6de869be74ac5eaf90f23e4b75b857 added extern g_cont:
https://github.com/xoseperez/espurna/blob/88e2eccccef3846845c2b43d5b58e3a24c61ef2d/code/espurna/utils.ino#L9-L12
but it is no longer defined in 'master' of esp8266/Arduino, now it is `cont_t* g_pcont`:
https://github.com/esp8266/Arduino/commit/5d5ea92a4d004ab009d5f642629946a0cb8893dd#diff-3fa12668b289ccb95b7ab334833a4ba8L35
This PR:
- added define check for core version when using g_cont/g_pcont
- updated travis envs to use newest platform, so this is tested
> Rename cont_t for Core 2.4.2 and higher

- code/html/custom.css
- code/html/custom.js
- code/html/index.html
Resolves #1010 
* revise first-time-use screen
* generate password (policy applies)
* hide/reveal password settings
* changed autocomplete='...' for some inputs to avoid accidental autocompletion
* split '#saveForm' into multiple '.form-settings' forms to avoid accidental autocompletion across panels
It would be nice if someone can test this on Safari 🍎
> Update password UI

- code/espurna/config/prototypes.h
- code/espurna/utils.ino
Amending #1195 with new ESP.getFreeContStack
Definition instead of function, -6 lines
> Inline getFreeStack and mention 2.5.0 helper method

- code/html/index.html
tnx to @agevant on gitter
>Also by hitting enter on the field hostname on general section you get a dump of the configuration in form of a json format, and as a result you get among other things your passwd and your api key in the json response. Is this a hidden feature or a bug?
Seems like all text fields on the web interface will reply with the current configuration in json format by hitting enter on any of them.
> Avoid implicit type="submit" buttons

- code/build.sh
- Make 'stat' Mac-aware (-c doesn't exist in BSD stat; it uses -f)
- Don't null the stdout - it might show useful compilation errors.
> Minor improvement to build.sh

- code/html/custom.css
- code/html/custom.js
- code/html/index.html
Amend #1182 and #1203 
-  attr() returns undefined with no attribute, method never set 'original'. 🤦‍♂️ likely happened mistaking getAttribute, which does return null for both present and unset attr (and not checking which branch was used locally, which was with native js getAttribute/hasAttribute)
- restoring old check for first password field length, which was accidentally removed. now '#layout' screen wont always fail password check
- also check for password validity before sending. this will issue client-side error instead of sending to device on '#password' screen
*I'll start looking into how to test ui interaction/presentation to avoid this in the future... And be more careful*
*edit:* minor css issue that i noticed from password ui update, it did not apply properly and neither …
> Fix-up style and form validation logic

- code/espurna/config/hardware.h
Developed against a [SM800-type device](https://fccid.io/2ANOO-SM800/Internal-Photos/Internal-Photos-3601477) (more-or-less equivalent Amazon products [1](https://www.amazon.com/Monitoring-Control-Smartphone-Compatibles-Assistant/dp/B0793RSYTV) [2](https://www.amazon.com/gp/product/B07837B9C1)), which has a similar circuit structure (ESP8266 module, pin assignments, LED polarity, switch polarity, energy monitoring chips and resistor values) to the XS-SSA05.
Changes:
- The LEDs are active-low (they are connected to the MCU pin on the low side)
- There are two LEDs, one red, one blue. I don't know if you have a convention for which one should be LED1 (which seems the only one editable from the web UI)
- The switch is active-low (pressing shorts to ground, pulled high by external circuitry) …
> (partial) fix for YiDian XS-SSA05 configs

- code/espurna/button.ino
- code/espurna/config/general.h
we should send only buttons events that have actions assigned to them or set BUTTON_MQTT_SEND_ALL_EVENTS to 1 to send everything
> Buttons send mqtt message for events with assigned actions to them

- code/espurna/config/sensors.h
- code/espurna/sensor.ino
- code/espurna/sensors/PZEM004TSensor.h
This PR is related to Issue #1051.
Basically, it is possible to add multiple PZEM004T devices in the same UART using the Multidrop TX concept.
You connect all devices in the same UART(Schematic above) and each device has a unique address, the sensor will ask for readings on each device.
My implementation will constantly ask for readings, and when ESPurna sensor loop will run, it'll get the last reading on all magnitudes. This will offload the sensor loop, which was causing reboots, etc on the previous implementation.
I added 3 commands:
* `pz.address [ADDRESS]`: 
* Print the addresses of all devices, with `ADDRESS` will issue `Set Address` command on the bus. This is to be used to program PZEM004T to a specific address.
* `pz.reset [DEV_INDEX]`: 
* Reset the Energy magnitude on all …
> Multiple PZEM004T on same UART

- code/espurna/config/arduino.h
- code/espurna/config/hardware.h
- code/espurna/config/progmem.h
- code/espurna/config/sensors.h
- code/espurna/config/types.h
- code/espurna/sensor.ino
- code/espurna/sensors/VL53L1XSensor.h
- code/html/custom.js
- code/platformio.ini
Support for VL53L1X Time-of-Flight Distance Sensor Carrier with Voltage Regulator, 400cm Max.
> This sensor is a carrier/breakout board for ST’s VL53L1X laser-ranging sensor, which offers fast and accurate ranging up to 4 m. It uses the time of flight (ToF) of invisible, eye-safe laser pulses to measure absolute distances independent of ambient lighting conditions and target characteristics like color, shape, and texture (though these things will affect the maximum range). The VL53L1X also features a programmable region of interest (ROI), so the full field of view can be reduced or divided into multiple zones. Distance measurements can be read through a digital I²C interface. The board includes a 2.8 V linear regulator and level-shifters that allow it to work over an input voltage range …
> Add support for VL53L1X sensor

- code/build.sh
`stat` is a bit weird on `macOS`, requiring the format to be passed using `-f` (instead of `-c`) and representing size in bytes as `%z` (instead of `%s`).
This PR adds some simple OS detection to execute `stat -f %z` on macOS, falling back to `stat -c %s`  on non-darwin systems.
---
Without this fix, building on macOS fails with the following output;
```Text
$ ./build.sh generic
--------------------------------------------------------------
ESPURNA FIRMWARE BUILDER
Building for version 1.13.3-a89b511f
--------------------------------------------------------------
Building web interface...
[20:07:10] Using gulpfile code/gulpfile.js
[20:07:10] Starting 'webui'...
[20:07:10] Starting 'webui_small'...
[20:07:10] Starting 'webui_sensor'...
[20:07:10] Starting 'webui_light'...
[20:07:10] …
```
> Use correct arguments for stat on macOS

- code/espurna/config/sensors.h
- code/espurna/sensor.ino
- code/espurna/sensors/PulseMeterSensor.h
I found debouncing to be required when using a "digital LDR" such as this one;
I copied the implementation from the event sensor, as it seemed pretty straightforward.
I don't think a configuration option is required for this, so it's hardcoded to 50ms right now (even then, if your power meter is flashing every 50ms then there's something wrong!).
> Add debouncing to pulse meter sensor

- code/espurna/config/arduino.h
- code/espurna/config/hardware.h
- code/platformio.ini
Back again with a newer bulb from the same company.
This one doesn't have RGB, it just has cool and warm leds.
To make it work well in the interface I had to put in dummy values (I used 255) for the RGB channels. The "white color temperature" feature is important for this bulb, since that behavior seems equivalent to what the regular firmware provides and disallows full power to both channels at the same time. Which *might* blow up the bulb as I've found out with the other one.
I did not see dummy values being used for the other bulbs, perhaps it simply hasn't been necessary. A nicer fix would probably involve a refactoring of the light channel code to not use hardcoded indices for the channels.
I don't know enough about your code to have confidence doing that. Let me know if the dummy …
> Add support for Lombex Lux Nova 2 Tunable White smart bulb

- code/espurna/relay.ino
`reload` / config update from web will push button 0 via digitalWrite(0)
Actually, no idea what issue to attach this to.
#1134 is rfbridge, but is quite old
#1214 is th16 that uses real relay
And both of them probably related to overwriting eeprom when rebooting / crashing, and that fix is already merged
> Fix wrong GPIO value for dummy relay

- code/espurna/utils.ino
Add an option for logging RSSI (wifi signal level) as part of the heartbeat messages when using InfluxDB.
Ideally I'd make this a runtime option with a toggle on the InfluxDB web page, but I haven't worked out how to do that yet.
> add rssi to InfluxDB heartbeat

- code/espurna/config/general.h
- code/espurna/ota.ino
This adds a new option ``OTA_MQTT_SUPPORT`` (disabled by default) that allows initiating OTA upgrades over MQTT. I also added a check on specified OTA URLs.
> Add OTA support over MQTT

- code/build.sh
- code/espurna/config/version.h
Keep -dev in the version all the time
Strip when building from tag, checking `TRAVIS_TAG=something` (CI release) or `git tag --contains HEAD` (local release)
Also do `git checkout -- version.h` after the script exists with tag present, to avoid accidentally committing it.
> APP_VERSION suffix

- code/espurna/config/general.h
- code/espurna/utils.ino
As referenced in #1400 comment
`hbReport` bitset, mapped from `Heartbeat::Report` enum (1 << 17 right now in size)
Set for both MQTT and InfluxDB (as they are the only targets now)
Keep old config active + allow to redefine them at build time
LOADAVG_REPORT -> HEARTBEAT_REPORT_LOADAVG
*Maybe* WIP, as there is only one setting for now.
No mode setting (but can disable using 0 for value)
No UI config / doc etc.
> Runtime heartbeat configuration

- README.md
- pre-commit
Minor README branch / version images issue. img.shields will not properly generate the image otherwise.
Not really obvious, as img.shields.io returns 404 + "error" image in the body, but github is making it look like network issue by not displaying any image at all
> Escape hyphens in img.shields.io urls

- code/espurna/mqtt.ino
Change mqttReset() behaviour so it does not immediately try to reconnect after just being disconnected.
Initial connection is the same, all consecutive are spaced out using reconnect delay.
Changing enabled / disabled will be like it is now - connect immediately on mqttReset() call
> MQTT reconnect delay based on last disconnection

- code/espurna/wifi.ino
Won't compile the Debug code in the final build which will help reduce the size of the build.
> Fix: Add Debug flag for compilation of wifiDebug() function

- code/espurna/ota.ino
avoid wdt reset when handling HTTP OTA
`debugSend()` actually saves the day here by doing`optimistic_yield()`, but it is possible to have DEBUG_SUPPORT=0
> yield() after handling OTA request

- code/espurna/ws.ino
+ fix crash on disconnection. `client->_tempObject` is not set to `nullptr` by the Client class, therefore is pointing *somewhere*
> Disconnect websocket when auth fails

- code/espurna/config/hardware.h
- code/platformio.ini
Newer AL-LC02 boards (or at least devices sold as such) **have different LED pins used** than original LC02 boards. 
From outside the device looks almost exactly as AL-LC11 (including voltage rating on input side) with exception of LED strip connector (RGBW so only 5 pins and label with description of 5 pins). Unfortunately pinout of new board is different from existing LC11.
Above mentioned differences unfortunately are not bullet proof way to distinguish devices as I have few LC-02 units with "old" label and "new" boards.
So only sure way to distinguish device with new board from one with old board is to disassemble the device and see markings on the PCB which will read "ESP-IR-A V1.4".
This pull request contains changes that add new firmware for such devices (arilux-al-lc02v14) by …
> Support for newer AL-LC02 boards with different pinout

- code/espurna/domoticz.ino
Support for control of RGB(WW) LED strips from Domoticz over MQTT.
Tested using AL-LC02 for the last ~3 weeks.
All comments highly appreciated.
References #291
> Support for RGB(WW) controlled using Domoticz MQTT messages

- code/espurna/rfbridge.ino
Since the function ``_rfbToArray`` is also called in RF_SUPPORT code, move the #if block.
> Fix compile error when RF_SUPPORT is enabled

- code/espurna/config/general.h
- code/espurna/system.ino
- code/espurna/utils.ino
- code/espurna/ws.ino
- code/html/index.html
- Heartbeat mode and interval configuration added to WebUI ADMIN page
- New option HEARTBEAT_REPEAT_STATUS: on device startup full heartbeat information and after HEARTBEAT_INTERVAL only STATUS report.
- Enhanced first heartbeat message - on device startup it will send heartbeat after ntpSynced will be true to get device time.
P.S. Code is tested. Web part is not compiled,and not tested, but I hope it will work :)
> Configure Heartbeat from WebUI & option HEARTBEAT_REPEAT_STATUS

- code/espurna/domoticz.ino
Fix for #1459
MQTT messages were processed regardless of the current idx.
Now it  only decodes messages with the right domoticz idx.
> ONLY processes Domoticz RGB MQTT Messages for the current idx

- code/espurna/relay.ino
When using the switches configuration "Zero or one switches active" the serial init are not full recognized by this relay board. The result is two relays on ON status.
When I click Switch#0 ON, and then Switch#1 ON, I need FIRST the relay 0 to OFF, and THEN relay 1 to ON, and viceversa.
> #1519 Esp-01 + 2ch 5v relay LC tech Exclusive relay on

- code/espurna/config/all.h
- code/espurna/config/deprecated.h
#1382 had changed the define to TELNET_AUTHENTICATION
Seamlessly replace old -> new and show compile time warning
> Add warning about TELNET_PASSWORD

- code/espurna/espurna.ino
loopDelay, hbMode, hbInterval are always using defaults, because settings are empty
> Setup settings before using them in system module

- code/espurna/config/prototypes.h
- code/espurna/homeassistant.ino
- code/espurna/ws.ino
- code/html/custom.js
- code/html/index.html
Fixes #1233 
Does involve sort-of a hack by knowing that DEBUG_MSG will not print timestamp if the last symbol is not new-line/cr-return.
> Print each HA config entry separately

- code/espurna/homeassistant.ino
The unique id allows the device name and entity_id in HA to be edited from the UI. The "device" info allows the entities to be associated with a single device and appear on the MQTT Integrations UI.
> Add unique id and device for better HA UI integration

- code/espurna/domoticz.ino
- refactor domoticz lights handler into separate function
- less debugging strings. show that domoticz had parsed values in a single line. -480 bytes off the firmware. (travis03 dev:631248 domoticz/update:630768)
- fix relay getter to return signed value, as intended
cc @karmacoma92
please check if it fixes the problem you are experiencing (from gitter https://gitter.im/tinkerman-cat/espurna?at=5c7651cd8a7def0752e40812)
> Domoticz lights refactoring

- code/espurna/config/prototypes.h
- code/espurna/terminal.ino
- code/espurna/utils.ino
Erase all 4 SDK sectors, as mentioned in https://github.com/xoseperez/espurna/issues/1595#issuecomment-469724250
@xoseperez looking at `flash.dump 1023` (last sector on 4M board) after running erase:
```
00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
------------------------------------------------------
0x0000:  00 FF FF FF AA 55 AA 55 02 00 00 00 1C 00 00 00      U U
...reset...
00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
------------------------------------------------------
0x0000:  00 FF FF FF AA 55 AA 55 03 00 00 00 1C 00 00 00      U U
```
Any idea what it is counting at 08? Flash writes? Resets?
> Fix ESP.eraseConfig() when using Core 2.3.0

- code/espurna/sensors/EventSensor.h
fix #1557 
- allow multiple interrupt handlers. check if other EventSensor is already handling and detach.
technically, it is not required to detach before reattachment, but while changing this i though it may be beneficial to still keep it but wire into the other sensors to track whats where. attachInterrupt from something else will detach EventSensor handler silently
- slightly faster method for debounce - cpu clock count instead of millis
> Event sensor: do not detach existing interrupts

- code/espurna/sensor.ino
- code/espurna/sensors/BMX280Sensor.h
- code/espurna/sensors/BaseSensor.h
- code/espurna/sensors/DallasSensor.h
Currently espurna magnitude precisions are hard-coded in sensor.ino. For example the default temperature precision is whole integer degrees Celsius.  This causes sensors such as the Dallas DS18B20 to miss 3 digits of extra precision.
This change modifies BaseSensor so that each sensor class can specify the number of decimals to represent its magnitude types. If the sensor does not override this virtual method, the default is to use the sensors.ino hard-coded values (i.e. fall back on previous method).
I also updated sensors BMX280 and Dallas OneWire are with the specified precision knowledge; tested with BME280 and Dallas DS18B20 sensors
> Sensors can determine precision of their magnitudes

- code/espurna/config/general.h
- code/espurna/mqtt.ino
- code/espurna/relay.ino
This feature is especially useful when using custom MQTT groups for relays. This adds the option to disable the reporting of relay statuses to MQTT, and report only to the custom MQTT groups (if defined).
> Add option to disable relay reporting to MQTT

- code/espurna/libs/SyncClientWrap.h
- code/espurna/ntp.ino
- fixes #1673 influxdb problem. should be compatible with all Core versions
- same issue. local include instead of global. pio allows such things, somehow ( also referenced in https://github.com/xoseperez/espurna/commit/e037dd15fbad66d961cf7f7a647ccb32d54839d4#commitcomment-32905447)
> Fix lib wrappers

- code/espurna/rfbridge.ino
Small fix - I think it makes sense to always send RF MQTT messages with retain off. I can't really think of a use case where you always want to retain the last rfin payload.
> Send RF MQTT message with retain off

- code/espurna/config/general.h
- code/espurna/espurna.ino
- code/espurna/system.ino
- code/espurna/utils.ino
- revert to 10 as default loop delay (#1574, https://github.com/xoseperez/espurna/issues/1631#issuecomment-480434926)
- call delay after callbacks are done, instead of calling it at the beginning (systemLoop is inside callbacks list)
> Safer loop delay default

- code/espurna/ws.ino
Fix for when `millis()` is less than wanted interval and last=0 (i.e. right after reboot or on millis overflow)
> Fix WS status message on boot

- code/espurna/sensor.ino
- code/espurna/settings.ino
- code/platformio.ini
resolve #1688 
- platformio `env:nodemcu-pzem004t`
- port settings setup from v2
No support for swapped `Serial`, just SoftwareSerial. PZEM library does `Serial.begin()` right in the constructor, so `Serial.swap()` call can go right after local sensor's `.begin()` if HW port is used.
SoftwareSerial support is always built in. PZEM library requires global define `PZEM004T_NO_SWSERIAL` an sensor here needs to conditionally depend on it, because it will strip tx+rx constructor.
545856 - 541896 = **3960** bytes of difference between SWS and no-SWS versions.
Not adding that here yet.
> PZEM004T: settings & dev board

- .travis.yml
- code/extra_scripts.py
- dist/patches/lwip_mtu_issue_1610.patch
fix #1610 
- triggers only when `ESPURNA_PIO_PATCH_ISSUE_1610=something` is specified
- conditionally patch & build lwip1 sources whenever build environment depends on it
- `build-lwip` and `patch-lwip` pio targets (use `pio run -e <env> -t <target>`) to trigger respective actions
make itself will track dependencies, and will not rebuild things. only overhead is extra `patch` and `cp` call.
platformio --silent flag suppresses all output, so no additional logging either
> pio: patch lwip1 MTU bug in travis

- code/espurna/homeassistant.ino
- code/espurna/light.ino
MQTT and HA brightness shall only be depended on LIGHT_PROVIDER != LIGHT_PROVIDER_NONE
This should fix #1292. I did a quick test with MQTT and web interface on `intermittech-quinled` target without observations. The homeassistant part is untested.
> MQTT and HA brightness

- code/build.sh
When using `build.sh` with `-d` option to relocate firmware storage location the script will fail with e.g.:
`mv: cannot move '.pioenvs/intermittech-quinled/firmware.bin' to '/firmware/espurna-1.13.6-dev/espurna-1.13.6-dev-intermittech-quinled.bin': No such file or directory`
This is cause by `mkdir` not using `$destination` variable.
> Fix path creation for firmware in build.sh

- code/espurna/web.ino
resolve #1660 
also, see https://github.com/tzapu/WiFiManager/blob/740005b21e5f5e5c6092dbd4d3037e4edee19113/WiFiManager.cpp#L749
as described in the issue, device receives a lot of simultaneous requests in very short amount of time.
this solves the original test-case example with Android 9 connecting to the AP with captive portal on.
the connecting device continues to send requests, but heap is no longer exhausted by keeping track on old connections.
> Close connection in notFound callback

- code/espurna/rtcmem.ino
- remove `rtcmem.test` command that was doing nothing
- replace memset with direct address writes. adds a debug with start/end address
- nicer `rtcmem.dump`. prints all usable block instead of just the ones used. still show the number of continuous blocks used in the status string at the top:
```
[080089] [RTCMEM] boot_status=0 status=0 blocks_used=8
[080090] 00 60001280: 00000000 00000001 00000002 00000003 00000004 00000005 00000006 00000007
[080091] 08 600012a0: 00000008 00000009 0000000a 0000000b 0000000c 0000000d 0000000e 0000000f
[080100] 16 600012c0: 00000010 00000011 00000012 00000013 00000014 00000015 00000016 00000017
[080109] 24 600012e0: 00000018 00000019 0000001a 0000001b 0000001c 0000001d 0000001e 0000001f
[080118] 32 60001300: 00000020 00000021 00000022 00000023 00000024 …
```
> Rtcmem update

- code/espurna/config/hardware.h
I noticed that the hardware profiles for the YJZK switches have `LED1_PIN_INVERSE` set to `0`, but these devices actually have inverted LED logic. I have corrected all 3 profiles in `hardware.h`.
> Fix LED Invert for YJZK Switches

- code/espurna/ws.ino
supersedes @KimNyholm https://github.com/xoseperez/espurna/pull/1733 (and fix related issues)
instead of define, use setting and define as default
will be documented in the wiki, but no webui exposure yet
> Configure WEB_REMOTE_DOMAIN at runtime

- code/espurna/config/hardware.h
Button is not visible from the outside, but can be wired outside or made more accessible by using a thin object, so it feels more like a button than a hole. The configuration should not cause issues if the button is not used at all.
> Add config for push button of Arilux AL-LC06

- code/espurna/crash.ino
- code/espurna/espurna.ino
- code/espurna/system.ino
- code/espurna/terminal.ino
- limit recorder stack size by 128 bytes (if we crash from sys context, size is ~4Kb. just pre-calculate it even before writing anything). additional 2 bytes used in eeprom to store it
- offset settings a bit more
- add possibility to disable storing both crash info and trace. To disable just trace, `sysTraceMax` can be set to 0. `sysSaveCrash` check is placed at the start of the crash callback.
Some general updates to comments.
Writer loop now uses the same logic as reader, shifting by address size and writing 32 bit value all at once.
> Update crash handler

- code/espurna/config/prototypes.h
- code/espurna/thinkspeak.ino
- code/espurna/utils.ino
- remove memory management in async client callbacks
- instead of global one, reference asyncclient from callback argument
- transfer temporary data-buffer to the global scope, avoid unintentional String copy
- implement strnstr to search onData payload
@JavierAder as discussed in #1752
Will try to leave it running with some sensor board.
There is another rough one, but *greatly* increasing firmware size:
https://github.com/xoseperez/espurna/compare/dev...mcspr:tspk/client-fixes
+1280bytes vs +<s>48</s>416bytes here
(supporting newest Core versions requires some tweaks to the networking part. I hope that can be reused somewhere to justify code size increase)
> Thingspeak: async client fixes

- code/platformio.ini
See: https://github.com/esp8266/Arduino/blob/8b1af68e3f996592c4b152e793cde81de4b8957d/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp#L725-L854
With this flag enabled, BearSSL is compiled with only these 4 ciphers:
```
TLS_RSA_WITH_AES_128_CBC_SHA256 / AES128-SHA256
TLS_RSA_WITH_AES_256_CBC_SHA256 / AES256-SHA256
TLS_RSA_WITH_AES_128_CBC_SHA / AES128-SHA
TLS_RSA_WITH_AES_256_CBC_SHA / AES256-SHA
```
Setting this build flag saves around 45.5KB in build size, which is very significant on low memory boards. I think it would be nice to enable this by default on the 512KB/1MB boards.
I did some quick checks and most (if not all) SSL server support these ciphers. To check a site, try: ``nmap --script ssl-enum-ciphers -p 443 google.com``
> Use basic BearSSL ciphers on low memory boards

- code/espurna/config/general.h
- code/espurna/config/types.h
- code/espurna/telnet.ino
This is a rewrite of the telnet module, it's no longer using ESPAsyncTCP but the regular WiFiServer/WiFiClient libraries. Tested it quite a bit, but more testing and feedback is appreciated.
> Telnet server: alternative to ESPAsyncTCP

- code/platformio.ini
Couple of fixes for #1805
- consistent upload_... naming - upload_protocol -> ota_upload_protocol
- actually use ota_upload_port, ota_upload_flags (tnx @Niek)
- recover espurna-core comment
As a bonus, recover espurna-core without wps and add the build with smartconfig
> Fixes for platformio builds

- code/espurna/web.ino
Using HTTP upgrade method described in the wiki and omitting auth headers:
https://github.com/xoseperez/espurna/wiki/OTA
```
curl -XPOST  \
-H "Content-Type: multipart/form-data" \
-F "filename=@.pioenvs/esp8266-1m-ota/firmware.bin" \
http://192.168.4.1/upgrade
```
Causes file handler to process OTA file and **write it to flash** and only then to go into the request handler, where it will issue auth error.
> Web OTA: check authentication result before accepting payload

- code/espurna/mdns.ino
- code/ota.py
This change makes managing ota updates of different builds of the same version (i.e. 1.13.6-dev) a little easier. Sample output is:
```
ESPurna OTA Manager v0.3
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
1  ALEXA-BRIDGE    10.1.5.151                                                                                                       0         0         0
2  ESP-RS-01       10.1.22.201      84:F3:EB:83:9F:0F  ESPURNA       1.13.6-dev    2019-05-20 00:32:55   MPK_RS_4CH                 4096      4096      2654208
3  ESP-WP-01       10.1.22.1        BC:DD:C2:23:2B:E3  ESPURNA       1.13.6-dev    2019-05-20 00:05:06   BLITZWOLF_BWSHPX           1024      1024      516096 …
```
> Build date

- code/espurna/light.ino
Will likely rebase & merge this as-is, so adding all 3 commits
- fixes #1575: limit generic brightness function to only 3 channels when RGBWW color option is ON, but white channels are not used
- implement old TODO: move gamma to progmem
- test: print channel description in the terminal `channel <id>` (i'd also move this as webui description?)
@hyteoo https://github.com/xoseperez/espurna/commit/4702fcfb92726396542791a99300df0cadad8972 restores pre-1.13.3 behaviour when `useWhite` is off 
if `useColor` is also off, it will apply brightness to all the channels (as it does right now)
> Light updates

- code/espurna/config/defaults.h
- code/espurna/config/deprecated.h
- code/espurna/config/hardware.h
- code/espurna/config/sensors.h
- code/espurna/sensor.ino
- code/espurna/sensors/EventSensor.h
- code/espurna/sensors/PulseMeterSensor.h
- code/platformio.ini
I know that there is going to be support for specifying all the things dynamically through browser but before that here is enhancement to support it now. This would also help for anyone finding #1815 as there is no code provided, only guidance
> Enable multiple Digital & Events

- code/extra_script_pre.py
A quick fix to allow building if there is no internet connection. I couldn't build the latest HEAD during a flight, I think the package update should be optional and not break building.
> Allow offline building - skip package updater if there is no connection

- code/espurna/config/prototypes.h
Compilation no longer fails when using F() / DEBUG_MSG_P in some specific cases like sensor classes:
```cpp
/home/builder/.platformio/packages/framework-arduinoespressif8266@1.20300.1/cores/esp8266/pgmspace.h:21:51: error: __c causes a section type conflict with __c
#define PSTR(s) (__extension__({static const char __c[] PROGMEM = (s); &__c[0];}))
^
```
#1370 as an example of where this did happen in class method
> Port PROGMEM from 2.5.0

- code/espurna/config/prototypes.h
- code/espurna/ntp.ino
- code/espurna/ws.ino
https://github.com/xoseperez/espurna/commit/21423431ceab1a6d792d3f6ba746b3166ec6cb5b#r34669282
https://github.com/xoseperez/espurna/commit/21423431ceab1a6d792d3f6ba746b3166ec6cb5b#r34669593
https://travis-ci.org/mcspr/espurna-nightly-builder/jobs/571178137#L454-L462
```
* espurna-1.13.6-dev-espurna-core-4MB.bin --- using global library storage
/home/travis/build/mcspr/espurna-nightly-builder/espurna/code/espurna/espurna.ino:737:1: error: 'ws_callbacks_t' does not name a type
/home/travis/build/mcspr/espurna-nightly-builder/espurna/code/espurna/espurna.ino:745:42: error: 'ws_on_send_callback_list_t' does not name a type
/home/travis/build/mcspr/espurna-nightly-builder/espurna/code/espurna/espurna.ino:745:70: error: ISO C++ forbids declaration of 'cbs' with no type [-fpermissive] …
```
> Fix WEB_SUPPORT=0 and missing definitions

- code/espurna/ws.ino
Fix #1843 & #1851 queues not clearing when disconnected
Fix continuously filling ws message queue when disconnected
> Fix WS memory leak when disconnected

- code/espurna/config/prototypes.h
- code/espurna/sensors/HLW8012Sensor.h
- code/espurna/ws.ino
Fix queue include when building without Home Assistant or Alexa (https://github.com/xoseperez/espurna/pull/1857#issuecomment-521735472)
Fix gcc warning about buffer size with unsigned char (which is kind of possible with GPIO_NONE, since Shelly 1PM should probably use it instead of real pins)
Change left over from the #1843 draft where a single loop handled all the queue elements at once. Since we are handling each thing separately, `new Buffer()` is called after each one finishes. That's not what we want, just create it on connection as it was before.
> Amend #1843

- code/espurna/web.ino
If you just access /reset the device reboots without any warning or need to authenticate
> Fixed a bug, any unauthenticated user could reset the device

- code/espurna/config/sensors.h
Fix #1866. Added some #ifndef guards on some BMX280 sensor defines, so they can be defined outside, read `custom.h`.
> Added #ifndef guard on some BMX280 defines.

- code/espurna/sensors/PMSX003Sensor.h
- code/espurna/sensors/SenseAirSensor.h
Check value range for PMSX005 and SenseAir CO2 sensor, and drop invalid value (temperature>=100°C or humidity<=1% or humidity>=100%) for MQTT reporting.
> Check value range for PMSX005 and SenseAir CO2 sensor

- code/espurna/config/rtcmem.h
- code/espurna/sensor.ino
- always use indexes with `eneTotal`
- fix `unsigned int` comparison with -1
- fix sensorID checks, use `magnitude.global` index directly as index
- migrate `pzemEneTotal` to `eneTotal`
- migrate `eneTotal` to `eneTotal0`
> Use indexed keys for energy saving

- code/espurna/config/prototypes.h
Arduino on windows machine shows this error:
```
In file included from sketch\config/all.h:36:0,
from C:\Programy\arduino_projekty\espurna_dev\code\espurna\espurna.ino:22:
sketch\config/prototypes.h:178:86: fatal error: static/letsencrypt_isrgroot_pem.h: No such file or directory
#include "static/letsencrypt_isrgroot_pem.h" // Default to LetsEncrypt X3 certificate
^
compilation terminated.
```
replace include paths from **static/** to **../static/** fix problem
> fix paths in prototypes.h

- code/espurna/wifi.ino
- code/platformio.ini
- Stop updating SoftAP hostname and password when changing hostname and password via WebUI / settings `reload`:
https://gitter.im/tinkerman-cat/espurna?at=5d65418f49ac051923be1f06
- show real ssid and psk values from current sdk configuration instead of using getSetting
- `WIFI.STA` command
> WiFi SoftAP fixes

- code/espurna/config/general.h
- code/espurna/config/prototypes.h
- code/espurna/wifi.ino
fix #614 ?
https://github.com/esp8266/Arduino/issues/5998#issuecomment-525332517
@arihantdaga can you try this one? if I understood correctly the required process. Can be adjusted a bit later
*edit:* not seeing any resets on initial connection. wifi.reset, wifi.ap commands work too.
If you can reliably reproduce lost IP addresses (either modem or none sleep), it would be interesting to see if this helps
> Test: etharp_gratuitous

- code/platformio.ini
- dist/arduino_ide/2.3.0/boards.local.txt
- dist/arduino_ide/latest/boards.local.txt
- dist/boards_local_txt.py
As noticed in #1873 
PubSubClient & Arduino MQTT use internal buffer, but the default value of 128 is pretty small
PubSubClient needs this value known at build-tme
ArduinoMQTT accepts constructor argument, but right now mqtt module depends on global object
> Update mqtt packet size to fit JSON payloads

- code/espurna/config/deprecated.h
- code/espurna/config/general.h
- code/espurna/config/prototypes.h
- code/espurna/homeassistant.ino
- code/espurna/mqtt.ino
- code/espurna/relay.ino
- code/espurna/settings.ino
- code/espurna/utils.ino
- code/espurna/ws.ino
- remove "platform" key, see #1440. this implicitly sets schema to "basic". pending some other clean-up regarding json and mqtt queueing, other schema can be added down the line 
- updated ws module queue elem to capture callbacks list, allows to pass more than one callback (for example, when they are generated on the fly as lambdas, see ha wsPost usage)
- modified method to send ha config to use global ws queue, fix #1762 problem with empty topics and ensure json allocation is consistent.
- use existing defines to set mqtt payload options. amend https://github.com/xoseperez/espurna/issues/1085, https://github.com/xoseperez/espurna/pull/1188 to use the set payload value. drop HOMEASSISTANT_PAYLOAD... defines. fixes #1883 
- update MQTT_STATUS_ONLINE/OFFLINE and RELAY_MQTT_ON/OFF with …
> Home Assistant updates

- code/espurna/config/general.h
- code/espurna/config/prototypes.h
- code/espurna/homeassistant.ino
- code/espurna/led.ino
- code/espurna/relay.ino
- customize TOGGLE payload
- match payload string when receiving data
- reference enum values instead of raw integers, spell out intended status
- remove dead code
amend #1885, capitalize `relayPayload...` suffix instead of using uppercase
add `relayPayloadToggle`
> MQTT: handle custom relay status payloads

- code/espurna/ota_httpupdate.ino
There is a wrong #if check in the HttpUpdate OTA implementation, causing HTTPS URLs not to work. This fixes the check.
> Fix HTTPS support with OTA_CLIENT_HTTPUPDATE

- code/espurna/light.ino
https://github.com/xoseperez/espurna/pull/1902#issuecomment-529144343
> Sending HSV commands works perfectly though, as does the HSV returned on mqtt, but again no physical output from device.
- revert toPWM type change, value could not fit values larger than 255
- try1 in handling map() output types
however, arduino map() is technically not entirely correct
https://github.com/PaulStoffregen/cores/blob/238b102ac46d1184e7055943cb5fe60bcb8eabbe/teensy4/wiring.h#L47
https://github.com/arduino/Arduino/issues/2466#issuecomment-69873889
https://forum.pjrc.com/threads/44503-map()-function-improvements
as I have not tried it with floating point inputs, it is likely broken
> lights: fix value2pwm range conversion

- code/espurna/libs/SecureClientHelpers.h
Took me a loooong time to figure out why ``config.on_check()`` was returning 1 (fingerprint) instead of 2 (CA). This fixes the function definition, added some debug lines as well to indicate which check is being used.
> Fix SSL check callback function definition

- code/espurna/config/dependencies.h
- code/espurna/config/prototypes.h
- code/espurna/terminal.ino
- code/espurna/ws.ino
https://gitter.im/tinkerman-cat/espurna?at=5d761a6e74c23124a2e2662f, @Niek 
Do we even need MDNS_CLIENT_SUPPORT then? I can resolve .local hostnames with built-in resolver, no need to use the external library. Only applies to lwip2 builds:
https://github.com/d-a-v/esp82xx-nonos-linklayer/blob/e23a07e5f9ccb43d36777c497fc34d044e3ecf3b/glue-lwip/arduino/lwipopts.h#L1164-L1168
> test: dns probing and netstat for terminal

- code/espurna/light.ino
- do provider update only after actually changing things
from https://github.com/xoseperez/espurna/compare/rules-rpn branch
> Lights: channel change detection

- code/espurna/light.ino
- capture step variable for the current transition
- use one-shot timer instead of recurring, restart from the timer callback
fixup 5d5f0f8b8cea987a45b2e33779a12176b151429b
changing channels too often, sometimes i had observed 'current' value become negative and result in 100% pwm output
> light: fix inconsistent transitions

- code/espurna/mqtt.ino
Hide `_mqtt_client_secure` under preprocessor check
> MQTT: fix building without secureclient with sync libraries

- code/espurna/config/general.h
- code/espurna/telnet.ino
Not sure if this is a useful feature to add, but I could see it being useful for some people. This basically adds the ability to telnet to an Espurna device that is NATed/firewalled. After sending the ``host:ip`` of a publicly reachable ncat listener to the MQTT topic ``telnet_reverse``, the device opens a telnet connection.
Note: untested on Async telnet server, but should work. There's one more issue that the first command is ignored, probably easiest is to move ``_telnetFirst = true`` to ``_telnetLoop`` / ``_telnetNewClient`` and set it to false in ``_telnetReverse``?
> Added support for reverse telnet

- code/espurna/ntp.ino
There's a compiler warning  in the NTP module when DEBUG support is disabled, this fixes it.
> Fix warning about unused variable if DEBUG support is disabled

- code/espurna/homeassistant.ino
got lost in 13c1a193280652358e678ab92e13b20266ee00be
discovery does not need it, but yaml config does
fix #1940
> HomeAssistant: add back platform="mqtt" to the yaml output

- .travis.yml
- code/build.sh
- travis_install.sh
- travis_script.sh
#1943 removed build.sh from test stage
- move install phase into a script, similar to travis_script move
- add `-w` (build WebUI) and `-b` (build binaries) to build.sh to separatly allow build one without the other. update travis_script to use `-w` when running webui test stage and both when running release stage
merge after #1951
> Restore WebUI builds in travis

- README.md
- update top badges row with latest master and dev binary builds info, move at the same line as downloads counter
- add extended notice about it too
- add sensors that were added during 1.13.5...now (
- add ECH1560 that was never mentioned
- minor clean-up
> README: add nightly builder releases and missing sensors

- code/espurna/config/general.h
- code/espurna/relay.ino
- code/espurna/scheduler.ino
- code/html/custom.js
- code/html/index.html
I have added an option to restore the last schedule state on the device boot.
This option is useful in case of power loss or any kind of device reset that you still want your schedules to continue as usual.
At the moment if the device had a "down time" while a scheduled action should have happen, your action wont get applied, with this new feature the device will check for the closest schedule action that should have happened before boot, and restore its state to the desired schedule action state.
I have also added an option in the "SWITCHES" menu to choose on which relay you would like this feature to run on.
Disclaimer: it only counts "Turn ON" and "Turn OFF" actions and ignores toggle actions
> Added restore last schedule support

- code/espurna/espurna.ino
- code/espurna/gpio.ino
fix #1958
- Read efuse registers to detect ESP8285. I can't find any documentation on that, esptool.py is my only source. (part of it is used for MAC, other bytes are not)
- Redo GPIO locking via std::bitset. Slightly nicer interface than basic shifts and easier to manage for this kind of thing specifically.
> gpio: detect esp8285 chip to allow the use of GPIO9 and GPIO10

- code/espurna/mqtt.ino
Bug on the setWill() call of the Arduin-MQTT library. The correct order of parameters is: topic, payload, retained, QoS.
See: https://github.com/256dpi/arduino-mqtt#api
> Bugfix: Arduino-MQTT setWill parameters

- code/espurna/sensors/DHTSensor.h
- increase time between HIGH and LOW switch per Adafruit library example, noticed by @JavierAder (https://github.com/xoseperez/espurna/issues/1918#issuecomment-537178533) and https://gitter.im/tinkerman-cat/espurna?at=5dc2cc76196ffb4db91888fc test by @structuralB
- move pinMode one block up to handle error condition (https://github.com/xoseperez/espurna/issues/1918#issuecomment-537178533)
- update _last_ok in begin() so that _read fails with ERROR_WARM_UP for 2 seconds after sensor is initialized.
> DHTSensor fixes

- code/espurna/config/prototypes.h
- code/espurna/homeassistant.ino
- code/espurna/mqtt.ino
- code/espurna/ws.ino
- create object for each specialized discovery function to avoid accidentally sharing data (adjusted fix from #1957 @kiddouk  )
- update mqtt discovery mechanism to enqueue topic+message pairs instead of directly sending them. most noticeable when using low-memory lwip or when just starting up the board, mqtt messages will fill the buffer and end up being lost. enqueue them manually ourselves and send one by one 
- update mqttSendRaw to return whether sending succeeds (PID > 0)
- update mqttSendRaw to log only small messages, avoid breaking ws / telnet debug queues with ha discovery payloads
- small update to ws debug struct to also use std::pair<String, String>
- fix (again) discovery not sending on reconnection; send flag will now reset to "enabled" value
resolves …
> HA: discovery fixes

- code/espurna/alexa.ino
- code/espurna/button.ino
- code/espurna/config/general.h
- code/espurna/config/prototypes.h
- code/espurna/domoticz.ino
- code/espurna/espurna.ino
- code/espurna/ir.ino
- code/espurna/led.ino
- code/espurna/relay.h
- code/espurna/relay.ino
- code/espurna/relay_config.h
- code/espurna/rfbridge.ino
- code/espurna/rpnrules.ino
- code/espurna/scheduler.ino
- code/espurna/sensor.ino
- code/espurna/terminal.ino
- code/espurna/thermostat.ino
- code/espurna/tuya.ino
- code/espurna/utils.h
- code/espurna/utils.ino
- code/espurna/web.ino
- add u32{to,from}String that use strtoul instead of itoa, add 0b 0o 0x prefix checks
- update boot mask to use kv storage instead of raw eeprom byte, add migration code
- update boot mask only after relay status really changes
- move relay prototypes.h entry into the relay.h, update .ino files to reference it  
- move relay header defaults (RELAY1_PIN etc.) to the relay_config.h
- refactor c struct into a simple c++ struct, add default and minimal pin+type+reset_pin based on id constructors, thus removing the need to push_back into the array.
- fix DUMMY_RELAY_COUNT=0, use default constructor via `_relays.resize(DUMMY_RELAY_COUNT + _relays.size)`
> Relay: update setup code, rework masking

- README.md
- code/espurna/config/dependencies.h
- code/espurna/config/deprecated.h
- code/espurna/ota_httpupdate.ino
- code/espurna/thinkspeak.ino
- code/espurna/web.ino
- code/platformio.ini
- use SecureClient in OTA HTTPUpdate (as was originally intended) @Niek 
- add warnings for asynctcp define, add warning about asynctcp and mqtt
- also a small change to the httpupdate mqtt integration to use scheduled function instead of local variable to capture url (I think it should work and I am not imagining this c++ lambda syntax)
- small comment change in pio ini to avoid confusion as to why we have all these platforms
- cleanup some module-specific defines back to avoid another confusion between secure client and asynctcp flags. while dependency flag makes sense and we have _AXTLS set as client, use module-local checks.
> Secure client / server cleanup

- code/platformio.ini
This is a follow-up of yesterday's PR: https://github.com/xoseperez/espurna/pull/2018
This should fix the WiFi connectivity issues.
> Upgrade to core 2.6.2, fixes WiFi issues

- code/scripts/memanalyzer.py
- small update to use `size` util instead of `objdump`, following the idea from esp8266/Arduino post-compilation script
- include .text1 in .text for newer Cores
> Scripts: memanalyzer can use size instead of objdump

- code/html/index.html
The letter-spacing in the "Modes" label (LED tab) gets broken when on small display (see the photo below)
Fixed it by changing from pure-u-0 to pure-u-1
> Fixed small aesthetic problem

- code/espurna/config/arduino.h
- code/espurna/config/hardware.h
- code/platformio.ini
#2055 
Also rename LOHAS_9W to LOHAS_E27_9W to match PIO env name and DEVICE _ MANUFACTURER pair
> Device: add LOHAS_E26_A19

- code/espurna/config/prototypes.h
- code/espurna/espurna.ino
- code/espurna/homeassistant.ino
- code/espurna/light.ino
- code/espurna/mqtt.ino
- code/espurna/nofuss.ino
- code/espurna/ntp.ino
- code/espurna/ota.h
- code/espurna/ota_arduinoota.ino
- code/espurna/relay.ino
- code/espurna/rfbridge.ino
- code/espurna/rfm69.ino
- code/espurna/rtcmem.ino
- code/espurna/sensor.ino
- code/espurna/thermostat.ino
- code/espurna/utils.h
- code/espurna/wifi.ino
- code/espurna/ws.h
- code/espurna/ws.ino
- code/espurna/ws_internal.h
- code/test/build/core.h
Revise ws include order because of #2067 failed builds:
https://travis-ci.com/mcspr/espurna-nightly-builder/jobs/269496547#L487-L493
Check Core build (c/p for now)
> Test: check core feature build
